development:
  adapter: postgresql
  database: busbase
  username: busbase
  password: androidbrasilprojetos
  host: localhost
  encode: utf8

production:
  adapter: postgresql
  database: busbase
  username: busbase
  password: androidbrasilprojetos
  host: localhost
  encode: utf8

test: &test
  adapter: postgresql
  database: busbase_test
  username: busbase
  password: androidbrasilprojetos
  host: localhost
  encode: utf8

cucumber:
  <<: *test
