require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ItinerariosController do

  def mock_itinerario(stubs={})
    @mock_itinerario ||= mock_model(Itinerario, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all itinerarios as @itinerarios" do
      Itinerario.stub(:all) { [mock_itinerario] }
      get :index
      assigns(:itinerarios).should eq([mock_itinerario])
    end
  end

  describe "GET show" do
    it "assigns the requested itinerario as @itinerario" do
      Itinerario.stub(:find).with("37") { mock_itinerario }
      get :show, :id => "37"
      assigns(:itinerario).should be(mock_itinerario)
    end
  end

  describe "GET new" do
    it "assigns a new itinerario as @itinerario" do
      Itinerario.stub(:new) { mock_itinerario }
      get :new
      assigns(:itinerario).should be(mock_itinerario)
    end
  end

  describe "GET edit" do
    it "assigns the requested itinerario as @itinerario" do
      Itinerario.stub(:find).with("37") { mock_itinerario }
      get :edit, :id => "37"
      assigns(:itinerario).should be(mock_itinerario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created itinerario as @itinerario" do
        Itinerario.stub(:new).with({'these' => 'params'}) { mock_itinerario(:save => true) }
        post :create, :itinerario => {'these' => 'params'}
        assigns(:itinerario).should be(mock_itinerario)
      end

      it "redirects to the created itinerario" do
        Itinerario.stub(:new) { mock_itinerario(:save => true) }
        post :create, :itinerario => {}
        response.should redirect_to(itinerario_url(mock_itinerario))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved itinerario as @itinerario" do
        Itinerario.stub(:new).with({'these' => 'params'}) { mock_itinerario(:save => false) }
        post :create, :itinerario => {'these' => 'params'}
        assigns(:itinerario).should be(mock_itinerario)
      end

      it "re-renders the 'new' template" do
        Itinerario.stub(:new) { mock_itinerario(:save => false) }
        post :create, :itinerario => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested itinerario" do
        Itinerario.stub(:find).with("37") { mock_itinerario }
        mock_itinerario.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :itinerario => {'these' => 'params'}
      end

      it "assigns the requested itinerario as @itinerario" do
        Itinerario.stub(:find) { mock_itinerario(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:itinerario).should be(mock_itinerario)
      end

      it "redirects to the itinerario" do
        Itinerario.stub(:find) { mock_itinerario(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(itinerario_url(mock_itinerario))
      end
    end

    describe "with invalid params" do
      it "assigns the itinerario as @itinerario" do
        Itinerario.stub(:find) { mock_itinerario(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:itinerario).should be(mock_itinerario)
      end

      it "re-renders the 'edit' template" do
        Itinerario.stub(:find) { mock_itinerario(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested itinerario" do
      Itinerario.stub(:find).with("37") { mock_itinerario }
      mock_itinerario.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the itinerarios list" do
      Itinerario.stub(:find) { mock_itinerario }
      delete :destroy, :id => "1"
      response.should redirect_to(itinerarios_url)
    end
  end

end
